using System.ComponentModel;

namespace MusicTheorySDK.Utils
{
    public enum Notes
    {
        [Position(11)]
        [NoteOf('C')]
        [Description("C♭")]
        CFlat,
        [Position(0)]
        [NoteOf('C')]
        C,
        [Position(1)]
        [NoteOf('C')]
        [Description("C♯")]
        CSharp,
        [Position(1)]
        [NoteOf('D')]
        [Description("D♭")]
        DFlat,
        [Position(2)]
        [NoteOf('D')]
        D,
        [Position(3)]
        [NoteOf('D')]
        [Description("D♯")]
        DSharp,
        [Position(3)]
        [NoteOf('E')]
        [Description("E♭")]
        EFlat,
        [Position(4)]
        [NoteOf('E')]
        E,
        [Position(5)]
        [NoteOf('E')]
        [Description("E♯")]
        ESharp,
        [Position(4)]
        [NoteOf('F')]
        [Description("F♭")]
        FFlat,
        [Position(5)]
        [NoteOf('F')]
        F,
        [Position(6)]
        [NoteOf('F')]
        [Description("F♯")]
        FSharp,
        [Position(6)]
        [NoteOf('G')]
        [Description("G♭")]
        GFlat,
        [Position(7)]
        [NoteOf('G')]
        G,
        [Position(8)]
        [NoteOf('G')]
        [Description("G♯")]
        GSharp,
        [Position(8)]
        [NoteOf('A')]
        [Description("A♭")]
        AFlat,
        [Position(9)]
        [NoteOf('A')]
        A,
        [Position(10)]
        [NoteOf('A')]
        [Description("A♯")]
        ASharp,
        [Position(10)]
        [NoteOf('B')]
        [Description("B♭")]
        BFlat,
        [Position(11)]
        [NoteOf('B')]
        B,
        [Position(0)]
        [NoteOf('B')]
        [Description("B♯")]
        BSharp
    }

    public enum Intervals
    {
        PerfectUnison,
        DiminishedSecond,
        MinorSecond,
        AugmentedUnison,
        MajorSecond,
        DiminishedThird,
        MinorThird,
        AugmentedSecond,
        MajorThird,
        DiminishedFourth,
        PerfectFourth,
        AugmentedThird,
        DiminishedFifth,
        AugmentedFourth,
        PerfectFifth,
        DiminishedSixth,
        MinorSixth,
        AugmentedFifth,
        MajorSixth,
        DiminishedSeventh,
        MinorSeventh,
        AugmentedSixth,
        MajorSeventh,
        DiminishedOctave,
        PerfectOctave,
        AugmentedSeventh
    }

    public enum Scales
    {
        Major,
        Minor
    }
}
